-keep class com.dexterous.** { *; }
-keep class com.google.gson.** { *; }
-keep class java.lang.reflect.Type
-keep class com.google.gson.reflect.TypeToken { *; }
-keep class * extends com.google.gson.reflect.TypeToken
